name: walkit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+3

# https://codewithandrea.com/articles/updated-formatter-dart-3-8/
environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # flutter_displaymode: ^0.6.0
  flutter_riverpod: ^2.6.1
  health: ^13.2.0
  lottie: ^3.3.1
  permission_handler: ^12.0.0
  device_info_plus: ^12.1.0
  riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  intl: ^0.20.0
  dio: ^5.9.0
  flutter_local_notifications: ^19.4.2
  avatar_plus: ^0.0.5
  google_sign_in: ^7.2.0
  firebase_core: ^4.1.0
  # firebase_auth: ^6.0.2
  # change_app_package_name: ^1.5.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  internet_connection_checker_plus: ^2.9.0
  share_plus: ^12.0.0
  app_links: ^6.4.1  # https://pub.dev/packages/app_links
  flutter_foreground_task: ^9.0.0
  crypto: ^3.0.6
  



dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/lotties/
    - assets/icons/
    - assets/logos/
    - shorebird.yaml

  fonts:
      # evil empire
    - family: EvilEmpire
      fonts:
        - asset: assets/fonts/Evil_Empire/EvilEmpire.otf
        
    - family: NataSans
      fonts:
        - asset: assets/fonts/Nata_Sans/NataSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Nata_Sans/NataSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nata_Sans/NataSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Nata_Sans/NataSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nata_Sans/NataSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nata_Sans/NataSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nata_Sans/NataSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nata_Sans/NataSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nata_Sans/NataSans-Black.ttf
          weight: 900
        - asset: assets/fonts/Nata_Sans/NataSans-VariableFont_wght.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
