// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgMav1DAd80ZBodemg6Hdg9S81pvLzmU',
    appId: '1:871288827965:android:d031d3e9a17f995f86fa54',
    messagingSenderId: '871288827965',
    projectId: 'walk-it-a2c3b',
    storageBucket: 'walk-it-a2c3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2oPdPEv_2i26OMR_Q1m2HCXqVfPjKqs',
    appId: '1:871288827965:ios:c586b77611d5582486fa54',
    messagingSenderId: '871288827965',
    projectId: 'walk-it-a2c3b',
    storageBucket: 'walk-it-a2c3b.firebasestorage.app',
    androidClientId: '871288827965-3qrkvupk12lvjhduuvv6nif7rpsuo8al.apps.googleusercontent.com',
    iosClientId: '871288827965-2bml28dn6tq5d21gfg75jk91evrr5jn2.apps.googleusercontent.com',
    iosBundleId: 'com.walkitapp.walkit',
  );

}